[book]
authors = ["Patrick Unick", "Eli Fischl"]
language = "en"
multilingual = false
src = "src"
title = "ApLang"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/snowfoxsh/aplang-book"